#  import os
 from together import Together

  client = Together(api_key=os.environ.get('TOGETHER_API_KEY'))
  response = client.completions.create(
    model="richardsonjordan92/google/gemma-2-9b-f815b3ed",
    prompt="",
    max_tokens=512,
    temperature=0.7,
    top_p=0.7,
    top_k=50,
    repetition_penalty=1,
    stream=True
    
)
print(response.choices[0].text)
